### ISSUE TITLE
Speed setting

### ISSUE THREAD

**Issue by GrayFace** [arcomage/arcomage-hd#18]
As of now the animations are way slower than in the original. An option to increase speed (or faster default) would be pretty important.

**Comment by tomchen** [comment]
Here TombOfVARN (the ru translator) said the same thing. My reply:
https://github.com/arcomage/arcomage-hd/pull/17#issuecomment-814843355

The speeded up version was just deployed 5 minutes ago.

If it's still slow to you, then it must be a browser performance issue that I can't solve on my side, but requires you to change to Chrome or Chrome engine-based browser (or update your computer 😂).

Tell me if it still feels slow.

**Comment by tomchen** [comment]
When I test the game with Firefox in Windows, when I click a card, it suddenly moves to the center. I removed an unnecessary box-shadow effect, now the latest version correctly shows the animated movement, everything seems to be fine with Windows Firefox in my 2015 gamer PC. I don't know if you and @TombOfVARN can see improvement in your browsers (TombOfVARN uses Firefox, not sure about GrayFace).

The latest version also fully supports tablet / mobile screen, you can try it.

**Comment by tomchen** [comment]
I didn't really planned for a Desktop Version but here is it:

https://github.com/arcomage/arcomage-hd#desktop-version

(Windows for now, I'll do MacOS and Linux later...)

(https://github.com/arcomage/arcomage-hd/issues/3)

I made it partly, no, mainly, because Firefox & Safari do not run the game very well. With Desktop Version, non Chrome-like browser user can play the game smoothly.

However it's just a Chrome wrapper that visits [arcomage.github.io](https://arcomage.github.io/), if you can use Chrome, you don't need this Desktop Version.

cc @TombOfVARN

**Comment by tomchen** [comment]
See also #66 [[Tutorial / solutions] What to do if the game is slow?](https://github.com/arcomage/arcomage-hd/issues/66) which I've just written.  If it's still slow in Chrome, the "Solution 2 Force Chrome to use dedicated GPU" might be worth a try on dual-GPU PCs.

I saw [Is there any way to force MM7 with grayface's to not use the integrated intel card?](https://www.celestialheavens.com/forum/10?p=385712) today and found forcing dedicated GPU might be a solution for ArcoMage HD being slow on some dual-GPU PCs. Indeed, by default Chrome does not use dedicated GPU at all when ArcoMage HD is running.
